package use_case.customize_voice;

import entity.AudioSettings;

/**
 * Output Data for the Customize Voice Use Case.
 */
public class CustomizeVoiceOutputData {

    private final AudioSettings settings;

    /**
     * Constructs a @code CustomizeVoiceOutputData object with the specified parameters.
     *
     * @param settings the AudioSettings generated by the use case, representing the customized voice properties.
     */
    public CustomizeVoiceOutputData(AudioSettings settings) {
        this.settings = settings;
    }

    /**
     * Retrieves the customized audio settings.
     *
     * @return the {@link AudioSettings} object containing the voice customization details.
     */
    public AudioSettings getAudioSettings() {
        return settings;
    }
}
